# Generated by Django 4.2 on 2023-04-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_num_guests'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('comments', '0004_remove_comments_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='address_type',
        ),
        migrations.AddField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-17T23:56:20.866658+00:00'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.PositiveIntegerField()),
                ('state', models.IntegerField(default=-2)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_comment', to='comments.comments')),
                ('reservations', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='reservations.reservation')),
                ('root_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='comments.comments')),
                ('user_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_reply', to='comments.comments')),
            ],
        ),
    ]
