# Generated by Django 4.2 on 2023-04-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comments_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-18T02:24:59.076287+00:00'),
        ),
    ]
