# Generated by Django 4.2 on 2023-04-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-19T03:29:07.041305+00:00'),
        ),
    ]
