# Generated by Django 4.2 on 2023-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-19T16:44:55.926734+00:00'),
        ),
    ]
