# Generated by Django 4.2 on 2023-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_comments_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='comment_author',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-19T17:40:36.607719+00:00'),
        ),
    ]
