# Generated by Django 4.2 on 2023-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_rename_author_comments_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-20T15:21:44.349302+00:00'),
        ),
    ]
