# Generated by Django 4.2 on 2023-04-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_alter_comments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-20T23:50:59.147818+00:00'),
        ),
    ]
