# Generated by Django 4.2 on 2023-04-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_alter_comments_content_alter_comments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2023-04-20T23:55:04.465101+00:00'),
        ),
    ]
