# Generated by Django 4.2 on 2023-04-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_property_reservation_to_book_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_awaiting_confirmation', 'Pending - Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled_awaiting_confirmation', 'Cancelled - Awaiting Confirmation'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('completed', 'Completed')], max_length=31),
        ),
    ]
