# Generated by Django 4.2 on 2023-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_guests',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
