# Generated by Django 4.2 on 2023-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='name',
            field=models.CharField(default='No Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
