# Generated by Django 4.2 on 2023-04-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymodel',
            old_name='pics',
            new_name='main_pic',
        ),
    ]
