# Generated by Django 4.2 on 2023-04-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_pics_propertymodel_main_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='city',
            field=models.CharField(default='Toronto', max_length=200),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='province',
            field=models.CharField(default='Ontario', max_length=200),
        ),
    ]
