# Generated by Django 4.2 on 2023-04-16 20:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertymodel_city_propertymodel_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertymodel')),
            ],
            options={
                'unique_together': {('property', 'date')},
            },
        ),
    ]
